import { EmergencyCategory, FirstAidInstruction } from '../models/types';

// Emergency categories for Bolivia (Spanish)
export const emergencyCategories: EmergencyCategory[] = [
  {
    id: 'cuts-wounds',
    name: 'Cortes y Heridas',
    description: 'Atención inmediata para heridas y sangrado',
    icon: 'medical',
    color: '#E74C3C',
    instructions: [],
  },
  {
    id: 'burns',
    name: 'Quemaduras',
    description: 'Tratamiento para quemaduras leves y severas',
    icon: 'fire',
    color: '#E67E22',
    instructions: [],
  },
  {
    id: 'heatstroke',
    name: 'Insolación',
    description: 'Cuidados para golpe de calor e insolación',
    icon: 'wb-sunny',
    color: '#F39C12',
    instructions: [],
  },
  {
    id: 'choking',
    name: 'Atragantamiento',
    description: 'Maniobra de Heimlich y liberación de vías respiratorias',
    icon: 'warning',
    color: '#8E44AD',
    instructions: [],
  },
  {
    id: 'fainting',
    name: 'Desmayo',
    description: 'Atención para pérdida de consciencia',
    icon: 'person',
    color: '#3498DB',
    instructions: [],
  },
  {
    id: 'cpr',
    name: 'RCP',
    description: 'Reanimación cardiopulmonar paso a paso',
    icon: 'favorite',
    color: '#E91E63',
    instructions: [],
  },
];

// First aid instructions for each category
export const firstAidInstructions: { [categoryId: string]: FirstAidInstruction[] } = {
  'cuts-wounds': [
    {
      id: 'cw-1',
      step: 1,
      title: 'Evaluar la herida',
      description: 'Examina la profundidad y gravedad del corte',
      audioText: 'Primero, evalúa qué tan profunda y grave es la herida. Si es muy profunda o no para de sangrar, llama al 110 inmediatamente.',
      duration: 8000,
    },
    {
      id: 'cw-2',
      step: 2,
      title: 'Lavar las manos',
      description: 'Lávate las manos antes de tocar la herida',
      audioText: 'Lávate las manos con agua y jabón antes de tocar la herida para evitar infecciones.',
      duration: 6000,
    },
    {
      id: 'cw-3',
      step: 3,
      title: 'Controlar el sangrado',
      description: 'Aplica presión directa con un paño limpio',
      audioText: 'Coloca un paño limpio o gasa sobre la herida y aplica presión firme y constante para detener el sangrado.',
      duration: 8000,
    },
    {
      id: 'cw-4',
      step: 4,
      title: 'Elevar la extremidad',
      description: 'Si es posible, eleva la parte afectada',
      audioText: 'Si la herida está en un brazo o pierna, elévala por encima del nivel del corazón para reducir el sangrado.',
      duration: 7000,
    },
    {
      id: 'cw-5',
      step: 5,
      title: 'Limpiar la herida',
      description: 'Limpia suavemente con agua limpia',
      audioText: 'Una vez que el sangrado se haya detenido, limpia la herida suavemente con agua limpia.',
      duration: 6000,
    },
    {
      id: 'cw-6',
      step: 6,
      title: 'Cubrir la herida',
      description: 'Cubre con vendaje estéril',
      audioText: 'Cubre la herida con un vendaje estéril o paño limpio. Cambia el vendaje si se empapa de sangre.',
      duration: 8000,
    },
  ],

  'burns': [
    {
      id: 'b-1',
      step: 1,
      title: 'Alejar del fuego',
      description: 'Retira a la persona de la fuente de calor',
      audioText: 'Primero, aleja a la persona de la fuente de calor o fuego de forma segura.',
      duration: 6000,
    },
    {
      id: 'b-2',
      step: 2,
      title: 'Enfriar la quemadura',
      description: 'Aplica agua fría por 10-20 minutos',
      audioText: 'Coloca la quemadura bajo agua fría corriente por 10 a 20 minutos para enfriar la piel.',
      duration: 8000,
    },
    {
      id: 'b-3',
      step: 3,
      title: 'Quitar ropa suelta',
      description: 'Retira ropa que no esté pegada a la piel',
      audioText: 'Quita cualquier ropa o joyería cerca de la quemadura, pero no remuevas nada que esté pegado a la piel.',
      duration: 8000,
    },
    {
      id: 'b-4',
      step: 4,
      title: 'No usar hielo',
      description: 'Nunca apliques hielo directamente',
      audioText: 'Nunca uses hielo, mantequilla o remedios caseros en la quemadura. Solo agua fría.',
      duration: 7000,
    },
    {
      id: 'b-5',
      step: 5,
      title: 'Cubrir la quemadura',
      description: 'Usa vendaje limpio y suelto',
      audioText: 'Cubre la quemadura con un vendaje limpio y suelto. No aprietes el vendaje.',
      duration: 6000,
    },
  ],

  'heatstroke': [
    {
      id: 'hs-1',
      step: 1,
      title: 'Mover a la sombra',
      description: 'Lleva a la persona a un lugar fresco',
      audioText: 'Inmediatamente mueve a la persona a un lugar fresco y con sombra, lejos del sol.',
      duration: 6000,
    },
    {
      id: 'hs-2',
      step: 2,
      title: 'Quitar ropa',
      description: 'Retira ropa innecesaria',
      audioText: 'Quita cualquier ropa innecesaria para ayudar a enfriar el cuerpo.',
      duration: 5000,
    },
    {
      id: 'hs-3',
      step: 3,
      title: 'Enfriar el cuerpo',
      description: 'Aplica agua fresca en la piel',
      audioText: 'Aplica agua fresca en la piel o usa toallas húmedas en el cuello, axilas e ingle.',
      duration: 8000,
    },
    {
      id: 'hs-4',
      step: 4,
      title: 'Dar agua',
      description: 'Si está consciente, da pequeños sorbos de agua',
      audioText: 'Si la persona está consciente y puede tragar, dale pequeños sorbos de agua fresca.',
      duration: 7000,
    },
    {
      id: 'hs-5',
      step: 5,
      title: 'Llamar emergencias',
      description: 'Si no mejora, llama al 110',
      audioText: 'Si la persona no mejora rápidamente o está inconsciente, llama al 110 inmediatamente.',
      duration: 8000,
    },
  ],

  'choking': [
    {
      id: 'ch-1',
      step: 1,
      title: 'Evaluar la situación',
      description: 'Pregunta si puede hablar o toser',
      audioText: '¿Puedes hablar o toser? Si puede toser, anímala a seguir tosiendo para expulsar el objeto.',
      duration: 8000,
    },
    {
      id: 'ch-2',
      step: 2,
      title: 'Posicionar las manos',
      description: 'Coloca las manos en el abdomen',
      audioText: 'Si no puede toser, párate detrás de la persona y coloca tus manos justo arriba del ombligo.',
      duration: 8000,
    },
    {
      id: 'ch-3',
      step: 3,
      title: 'Maniobra de Heimlich',
      description: 'Empuje rápido hacia arriba',
      audioText: 'Haz un puño con una mano y colócala sobre la otra. Empuja rápida y firmemente hacia arriba.',
      duration: 8000,
    },
    {
      id: 'ch-4',
      step: 4,
      title: 'Repetir',
      description: 'Continúa hasta que salga el objeto',
      audioText: 'Repite las compresiones hasta que el objeto salga o la persona pueda respirar.',
      duration: 7000,
    },
    {
      id: 'ch-5',
      step: 5,
      title: 'Llamar emergencias',
      description: 'Si no funciona, llama al 110',
      audioText: 'Si la maniobra no funciona después de varios intentos, llama al 110 inmediatamente.',
      duration: 8000,
    },
  ],

  'fainting': [
    {
      id: 'f-1',
      step: 1,
      title: 'Acostar a la persona',
      description: 'Coloca a la persona boca arriba',
      audioText: 'Acuesta a la persona boca arriba en una superficie plana.',
      duration: 5000,
    },
    {
      id: 'f-2',
      step: 2,
      title: 'Elevar las piernas',
      description: 'Levanta las piernas 8-12 pulgadas',
      audioText: 'Eleva las piernas de la persona unos 20 a 30 centímetros para mejorar el flujo sanguíneo al cerebro.',
      duration: 8000,
    },
    {
      id: 'f-3',
      step: 3,
      title: 'Verificar respiración',
      description: 'Asegúrate de que esté respirando',
      audioText: 'Verifica que la persona esté respirando normalmente y que sus vías respiratorias estén libres.',
      duration: 7000,
    },
    {
      id: 'f-4',
      step: 4,
      title: 'Aflojar ropa',
      description: 'Suelta ropa ajustada',
      audioText: 'Afloja cualquier ropa ajustada, especialmente alrededor del cuello.',
      duration: 6000,
    },
    {
      id: 'f-5',
      step: 5,
      title: 'Esperar la recuperación',
      description: 'No la levantes inmediatamente',
      audioText: 'Espera a que la persona recupere la consciencia. No la levantes inmediatamente cuando despierte.',
      duration: 8000,
    },
  ],

  'cpr': [
    {
      id: 'cpr-1',
      step: 1,
      title: 'Verificar consciencia',
      description: 'Toca y grita para ver si responde',
      audioText: 'Toca los hombros de la persona y grita: ¿Estás bien? Si no responde, prepárate para RCP.',
      duration: 8000,
    },
    {
      id: 'cpr-2',
      step: 2,
      title: 'Llamar al 110',
      description: 'Pide ayuda médica inmediatamente',
      audioText: 'Llama al 110 inmediatamente o pide a alguien que lo haga mientras preparas la RCP.',
      duration: 7000,
    },
    {
      id: 'cpr-3',
      step: 3,
      title: 'Posicionar las manos',
      description: 'Centro del pecho, entre los pezones',
      audioText: 'Coloca el talón de una mano en el centro del pecho, entre los pezones. Pon la otra mano encima.',
      duration: 8000,
    },
    {
      id: 'cpr-4',
      step: 4,
      title: 'Compresiones',
      description: '30 compresiones rápidas y profundas',
      audioText: 'Empuja fuerte y rápido al menos 5 centímetros de profundidad. Haz 30 compresiones a ritmo de 100-120 por minuto.',
      duration: 10000,
    },
    {
      id: 'cpr-5',
      step: 5,
      title: 'Ventilaciones',
      description: '2 respiraciones de rescate',
      audioText: 'Inclina la cabeza hacia atrás, levanta el mentón y da 2 respiraciones lentas en la boca.',
      duration: 8000,
    },
    {
      id: 'cpr-6',
      step: 6,
      title: 'Continuar ciclos',
      description: 'Repite 30 compresiones y 2 respiraciones',
      audioText: 'Continúa con ciclos de 30 compresiones y 2 respiraciones hasta que llegue ayuda médica.',
      duration: 8000,
    },
  ],
};

// Update categories with their instructions
emergencyCategories.forEach(category => {
  category.instructions = firstAidInstructions[category.id] || [];
});

export default emergencyCategories;
